name: Deploy to GitHub Pages

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && (github.event_name == 'workflow_dispatch' || contains(github.event.base_ref, 'refs/heads/main'))
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build Remix app in SPA mode
        run: |
          yarn app build
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_ETH_ORDER_ADDRESS: ${{ vars.VITE_ETH_ORDER_ADDRESS }}
          VITE_ARB_ORDER_ADDRESS: ${{ vars.VITE_ARB_ORDER_ADDRESS }}
          VITE_ETH_RECEIVER_ADDRESS: ${{ vars.VITE_ETH_RECEIVER_ADDRESS }}
          VITE_ARB_RECEIVER_ADDRESS: ${{ vars.VITE_ARB_RECEIVER_ADDRESS }}
          VITE_REQUIRED_ORDER_AMOUNT: ${{ vars.VITE_REQUIRED_ORDER_AMOUNT }}
      
      - name: Setup Git for GitHub Pages deployment
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git config --global init.defaultBranch main
      
      - name: Create GitHub Pages Repository
        run: |
          mkdir -p gh-pages-repo
          cp -r app/build/client/* gh-pages-repo/
          cp gh-pages-repo/index.html gh-pages-repo/404.html
          echo "dex.orderly.network" > gh-pages-repo/CNAME
          # Add .nojekyll file to disable Jekyll processing
          touch gh-pages-repo/.nojekyll
      
      - name: Deploy to GitHub Pages
        run: |
          cd gh-pages-repo
          git init
          git branch -m main
          git remote add origin https://${{ secrets.GH_PAGES_DEPLOY_TOKEN }}@github.com/OrderlyNetworkDexCreator/orderlynetworkdexcreator.github.io.git
          git add -A
          git commit -m "Deploy: $(date +%Y-%m-%d_%H-%M-%S)"
          git push -f origin main 